name: MineTime
main: no.brisner.minetime.Minetime
version: 0.1
commands:
  tokens:
      description: Main command
  donate:
      description: Donating command
  password:
      description: Make me member command